language: android
jdk: oraclejdk17
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2


    # The SDK version used to compile your project
    - android-33

    # Support library
    - extra-android-support
    - extra-android-m2repository
    - sys-img-x86_64-android-22
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - android list target

